### PR TITLE
created draw samples .py

### PR DESCRIPTION
**Pull request by lisebraaten**
Created draw_samples.py with docstring

### CODE REVIEW

**Review by hwilliams10 — CHANGES_REQUESTED** [review]
I think all functions need to be defined in the `samplingsimulatorpy.py` file instead of in their own files.
I could be wrong, but this seems to be the case in all the examples we've been shown.

**Comment by tguo9** [comment]
I think either way is fine. For python, I checked the third chapter of the book, the structures can be in different files. https://ubc-mds.github.io/py-pkgs/package-structure.html

**Comment by lisebraaten** [comment]
I just moved the draw samples function to the samplingssimulatorpy.py file and deleted the draw_samples.py file. Thanks guys!

**Review by tguo9 — APPROVED** [review]
Looks good

**Review by hwilliams10 — APPROVED** [review]
looks good

**Pull request merged**
